#!/usr/bin/env bash
# This script displays information about subdomains of a domain

domain="$1"
subdomain="$2"

if [ -z "$subdomain" ]; then
  subdomains=("www" "lb-01" "web-01" "web-02")
else
  subdomains=("$subdomain")
fi

for sub in "${subdomains[@]}"; do
  output=$(dig "$sub.$domain" +short)
  record_type=$(echo "$output" | awk '{print $2}')
  destination=$(echo "$output" | awk '{print $3}')
  echo "The subdomain $sub is a $record_type record and points to $destination"
done
