#!/usr/bin/env bash
# This script configures Nginx to add a custom X-Served-By header

# Update packages
sudo apt update

# Install Nginx
sudo apt install -y nginx

# Configure custom header
echo 'add_header X-Served-By $hostname;' | sudo tee -a /etc/nginx/conf.d/custom_header.conf

# Restart Nginx
sudo systemctl restart nginx

