#!/usr/bin/env bash
# This script configures Nginx with a custom HTTP response header

# Install Nginx
apt-get update
apt-get -y install nginx

# Configure custom HTTP response header
echo 'add_header X-Served-By 128485-web-01;' | sudo tee -a /etc/nginx/sites-available/default

# Restart Nginx
systemctl reload nginx 
