#!/usr/bin/env bash
# This script configures Nginx to include a custom response header
# shellcheck disable=SC2154

sudo apt-get update
sudo apt-get install -y nginx
sudo sed -i 's/# server_tokens off;/server_tokens off;\n        add_header X-Served-By $hostname;/g' /etc/nginx/nginx.conf
sudo service nginx restart