#!/usr/bin/env bash
# This script installs and configures HAProxy as a load balancer

# Install HAProxy
apt-get update
apt-get -y install haproxy

# Configure HAProxy
cat > /etc/haproxy/haproxy.cfg <<EOF
frontend web
    bind *:80
    mode http
    default_backend servers

backend servers
    mode http
    balance roundrobin
    server web-01 [STUDENT_ID]-web-01:80 check
    server web-02 [STUDENT_ID]-web-02:80 check
EOF

# Enable HAProxy init script
sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

# Restart HAProxy
service haproxy restart

