#!/usr/bin/env bash
# Configure HAProxy as a load balancer

# Update system packages
sudo apt-get update

# Install HAProxy
sudo apt-get install -y haproxy

# Configure HAProxy
sudo sed -i 's/^ENABLED=.*/ENABLED=1/' /etc/default/haproxy

# Create HAProxy configuration file
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOT
frontend webapp
    bind *:80
    mode http
    default_backend servers

backend servers
    mode http
    balance roundrobin
    server web-01 128485-web-01:80 check
    server web-02 128485-web-02:80 check
EOT

# Restart HAProxy
sudo systemctl restart haproxy
 
