#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
# using while loop

svar=1

while [[ $svar -lt 11 ]];
do
	if (( svar == 9))
	then
		echo "Best School"
		echo "Hi"
	else
		echo "Best School"
	fi
	((svar++))
done
