#!/usr/bin/env bash
# This script is displaying "Best School" 10 times

svar=1

while [ "$svar" -lt 11 ]
do
	if [ "$svar" -eq 4 ]
	then
		echo "bad luck"
	elif [ "$svar" -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	(( svar++ ))
done
