#!/usr/bin/env bash
# a Bash script that displays numbers from 1 to 20

svar=1

while [ $svar -lt 21 ]
do
	echo $svar
	case $svar in
		4)
			echo "bad luck from China";;
		9)
			echo "bad luck from Japan";;
		17)
			echo "bad luck from Italy";;
	esac
	(( svar++ ))
done
