#!/usr/bin/env bash
# a Bash script that displays numbers from 1 to 20

hour=0

while [[ $hour -lt 13 ]];
do
	min=1
	echo "Hour: $hour"

	while [[ $min -lt 60 ]]
	do
		echo $min
		(( min++ ))
	done
	(( hour++ ))
done
