#!/usr/bin/env bash
sed -i 's/user\s*root;/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/listen\s*80;/listen 8080;/' /etc/nginx/nginx.conf
chown -R nginx:nginx /var/lib/nginx
nginx -t
service nginx reload

